### ISSUE TITLE
页面无法显示登录二维码

### ISSUE THREAD

**Issue by jiangwenfan** [mewhz/Tools#1]
我安装了chrome的driver,运行程序，打开浏览器新窗口中的url地址栏中显示"data:,"，页面空白，不知道该如何解决。
我尝试将url链接更换为"https://www.baidu.com"页面打开并显示成功。

**Comment by mewhz** [comment]
您好，填体温这个代码，部分地方是针对我们学校的腾讯文档书写，所以需要根据自己的文档来写自己的url与代码调整，但是貌似腾讯修复了这种自动写体温的办法....QAQ
